Added README

diff --git a/workspace/src/network_testing/rosbarc_network b/workspace/src/network_testing/rosbarc_network
--- a/workspace/src/network_testing/rosbarc_network
+++ b/workspace/src/network_testing/rosbarc_network
@@ -1,34 +1,64 @@
 #!/bin/bash
 
+
+source=1
+if [ "${BASH_SOURCE[0]}" != "${0}" ]; then
+    source=0
+fi
+
+source_exit() {
+    if [ ${source} -eq 1 ]; then
+        exit ${1}
+    fi
+}
+
+error_handle() { 
+    echo "Invalid syntax. Use 'rosbarc_network -h' for help on usage" >&2
+    source_exit 1
+}
+
+if [ $# -lt 1 ]; then
+    error_handle
+fi
+
 case $1 in
 
-    -m)
+    "-m" )
         source ./sshcar -s
         master=$(rosparam get master 2> /dev/null)
-        if [ -n master ]; then
+        echo "$master"
+        if [ -n "${master}" ]; then
             echo "According to the parameter server, a master already exists.
             If you would like to make this car the master, either
             stop the current master and restart the network with this car, or
-            take this car off the current network and make it a master on a new network."
+            take this car off the current network and make it a master on a new network." >&2
+            source_exit 1
         else
             roslaunch network_testing mastercar.launch car:=$(hostname) & 
         fi
-        exit 0
     ;;
 
-    -s)
-        if [ $# = 2 ]; then
+    "-s" )
+        if [ $# -eq 2 ]; then
             ./sshcar -l ${2}
+        elif [$# -eq 1 ]; then
+            roslaunch network_testing slavecar.launch car:=$(hostname) &
         else
-            echo "Invalid syntax: use 'rosbarc_network -h' for help on usage"
+            error_handle
         fi
         
     ;;
 
-    -h)
+    "-h" )
         echo "Manual:
             source rosbarc_network [FLAG] [ARG]
         "
     ;;
 
+    * )
+        error_handle
+    ;;
+
 esac
+
+source_exit 0
diff --git a/workspace/src/network_testing/sshcar b/workspace/src/network_testing/sshcar
--- a/workspace/src/network_testing/sshcar
+++ b/workspace/src/network_testing/sshcar
@@ -9,17 +9,42 @@ env_var() {
 
 }
 
+source=1
+if [ "${BASH_SOURCE[0]}" != "${0}" ]; then
+    source=0    #source is used to call script
+fi
+
+source_exit() {
+    if [ ${source} -eq 1 ]; then
+        exit ${1}
+    fi
+}
+
+source_warn() {
+    
+     if [ ${source} -eq 1 ] ; then
+        echo "source was not used when calling the script. Nothing in the current terminal has changed."
+     fi
+
+}
 
 if [ $# -eq 2 ]; then
 
 case "$1" in
     "-s" )
+     source_warn
      env_var ${2} $(hostname)
 #    export ROS_MASTER_URI=http://${2}.local:11311
 #    export ROS_IP=$(hostname).local
 #    export ROS_HOSTNAME=$(hostname).local
     ;;
     
+    "-l" )
+    ssh -t ${2}.local "export ROS_MASTER_URI=http://$(hostname).local:11311; export ROS_IP=${2}.local; export ROS_HOSTNAME=${2}.local;
+    
+        roslaunch network_testing slavecar.launch car:=${2}; bash -i -c echo hi"
+    ;;
+
     * )
     
     ssh -t ${2}.local "export ROS_MASTER_URI=http://${1}.local:11311; export ROS_IP=${2}.local; export ROS_HOSTNAME=${2}.local; bash"
@@ -64,18 +89,15 @@ case "$1" in
     ;;
     "-s" )
     
+     if [ ${source} -eq 1 ] ; then
+        echo "source was not used when calling the script. Nothing in the current terminal has changed."
+     fi
      env_var $(hostname) $(hostname)
 #    export ROS_MASTER_URI=http://$(hostname).local:11311
 #    export ROS_IP=$(hostname).local
 #    export ROS_HOSTNAME=$(hostname).local
     ;;
    
-    "-l" )
-    ssh -t ${2}.local "export ROS_MASTER_URI=http://$(hostname).local:11311; export ROS_IP=${2}.local; export ROS_HOSTNAME=${2}.local;
-    
-        roslaunch network_testing slavecar.launch car:=${2}; bash"
-    ;;
-
     * )
 
     ssh -t ${1}.local "export ROS_MASTER_URI=http://$(hostname).local:11311; export ROS_IP=${1}.local; export ROS_HOSTNAME=${1}.local; bash"
@@ -83,8 +105,10 @@ case "$1" in
 esac
 
 else
-    echo "Invalid syntax. Type 'sshcar -h' for help."
+    echo "Invalid syntax. Type 'sshcar -h' for help." >&2
+    source_exit 1
     
 fi
 
 
+source_exit 0
